/**
 * Bootcamp title: Amdocs Java Developer
 * Instructor: Rodrigo Tavares
 * Example adapted by: Charles Fernandes de Souza
 * Date: January 15, 2022
 */

CREATE DATABASE loja
USE loja

CREATE TABLE PRODUTOS (
    CODIGO        INT         NOT NULL ,
    DESCRICAO     VARCHAR(50) NOT NULL ,
    DATA_VALIDADE DATETIME,
    EAN           VARCHAR(15) NOT NULL,
    IND_INATIVO   INT         NOT NULL DEFAULT 0
);

ALTER TABLE    PRODUTOS 
	ADD CONSTRAINT PK_PRODUTOS
		PRIMARY KEY   (CODIGO)
;

CREATE INDEX IDX_PRODUTOS_EAN
	ON PRODUTOS (EAN)
;


INSERT INTO PRODUTOS VALUES (1, 'Nome do Protudo', GETDATE(), '1234567890', 0);

SELECT * FROM PRODUTOS

SELECT GETDATE()

INSERT INTO PRODUTOS(CODIGO, DESCRICAO, EAN) VALUES (2, 'Nome do Protudo2', '1234567890');

SELECT * 
	FROM PRODUTOS 
WHERE CODIGO = 2

SELECT * 
 FROM PRODUTOS
WHERE DESCRICAO LIKE 'Produto'

SELECT * 
 FROM PRODUTOS
WHERE DESCRICAO LIKE '%Produto'

SELECT * 
 FROM PRODUTOS
WHERE DESCRICAO LIKE '%Produto%'

SELECT COUNT(*) AS TOTAL
  FROM PRODUTOS

CREATE TABLE LOJAS(
    CODIGO        INT         NOT NULL ,
    NOME          VARCHAR(50) NOT NULL ,
    DATA_VALIDADE DATETIME,
    IND_INATIVO   INT         NOT NULL DEFAULT 0,
	CONSTRAINT LOJA_PK PRIMARY KEY(CODIGO)
);

INSERT INTO LOJAS (CODIGO, NOME) VALUES (1000, 'Filial Socorro');
INSERT INTO LOJAS (CODIGO, NOME) VALUES (2000, 'Filial São Carlos');
INSERT INTO LOJAS (CODIGO, NOME) VALUES (3000, 'Filial São Natal');

SELECT * FROM LOJAS

CREATE TABLE ESTOQUE(
  CODIGO_PRODUTO INT     NOT NULL,
  CODIGO_FILIAL  INT     NOT NULL,
  QUANTIDADE     DECIMAL NOT NULL DEFAULT 0,
  CONSTRAINT ESTOQUE_PK PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)
);

ALTER TABLE ESTOQUE
 ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
     FOREIGN KEY (CODIGO_PRODUTO)
	 REFERENCES PRODUTOS(CODIGO)
;

ALTER TABLE ESTOQUE
 ADD CONSTRAINT FK_ESTOQUE_LOJAS
     FOREIGN KEY (CODIGO_FILIAL)
	 REFERENCES LOJAS(CODIGO)
;

ALTER TABLE ESTOQUE
 DROP CONSTRAINT FK_ESTOQUE_LOJAS

INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE)VALUES (1, 1000, 10)

SELECT E.CODIGO_FILIAL
  , L.NOME
  FROM ESTOQUE E INNER JOIN LOJAS L
    ON E.CODIGO_FILIAL = L.CODIGO

SELECT E.CODIGO_FILIAL
  , L.NOME
  , E.CODIGO_PRODUTO
  , P.DESCRICAO
  , E.QUANTIDADE
  FROM ESTOQUE E INNER JOIN LOJAS L
    ON E.CODIGO_FILIAL = L.CODIGO
     INNER JOIN PRODUTOS P
      ON E.CODIGO_PRODUTO = P.CODIGO

